FROM pytorch/pytorch:1.9.0-cuda11.1-cudnn8-runtime

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends g++ curl sudo wget && \
    apt-get -y clean && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY transformers_custom transformers_custom
COPY schema schema
COPY utils utils
COPY mygenerate.py .
COPY demo_api.py .

CMD ["uvicorn", "demo_api:app", "--host", "0.0.0.0"]
EXPOSE 8000
